In [1]:
import pandas as pd
df = pd.read_csv("stock_data.csv")
df = pd.read_csv("stock_data.csv",header = 1)
df

  GOOGL          27.82   87   845     larry page
0   WMT           4.61  484    65           n.a.
1  MSFT             -1   85    64     bill gates
2  RIL   not available   50  1023  mukesh ambani
3  TATA            5.6   -1  n.a.     ratan tata

In [2]:
df = pd.read_csv("stock_data.csv",header = None)
df

         0              1        2      3              4
0  tickers            eps  revenue  price         people
1    GOOGL          27.82       87    845     larry page
2      WMT           4.61      484     65           n.a.
3     MSFT             -1       85     64     bill gates
4     RIL   not available       50   1023  mukesh ambani
5     TATA            5.6       -1   n.a.     ratan tata

In [3]:
df = pd.read_csv("stock_data.csv",header = None, names=['ticket','eps','revenue','price','people'])
df

    ticket            eps  revenue  price         people
0  tickers            eps  revenue  price         people
1    GOOGL          27.82       87    845     larry page
2      WMT           4.61      484     65           n.a.
3     MSFT             -1       85     64     bill gates
4     RIL   not available       50   1023  mukesh ambani
5     TATA            5.6       -1   n.a.     ratan tata

In [4]:
df = pd.read_csv("stock_data.csv",nrows = 3)
df

  tickers    eps  revenue  price      people
0   GOOGL  27.82       87    845  larry page
1     WMT   4.61      484     65        n.a.
2    MSFT  -1.00       85     64  bill gates

In [5]:
df = pd.read_csv("stock_data.csv",na_values=["not available","n.a."])
df

  tickers    eps  revenue   price         people
0   GOOGL  27.82       87   845.0     larry page
1     WMT   4.61      484    65.0            NaN
2    MSFT  -1.00       85    64.0     bill gates
3    RIL     NaN       50  1023.0  mukesh ambani
4    TATA   5.60       -1     NaN     ratan tata

In [6]:
df = pd.read_csv("stock_data.csv",na_values={
        'eps': ["not available","n.a."],
        'revenue' : ["not available","n.a.",-1],
        'people' : ["not available","n.a."]
    })
df

  tickers    eps  revenue price         people
0   GOOGL  27.82     87.0   845     larry page
1     WMT   4.61    484.0    65            NaN
2    MSFT  -1.00     85.0    64     bill gates
3    RIL     NaN     50.0  1023  mukesh ambani
4    TATA   5.60      NaN  n.a.     ratan tata

In [7]:
df.to_csv("new.csv",index = False)
df

  tickers    eps  revenue price         people
0   GOOGL  27.82     87.0   845     larry page
1     WMT   4.61    484.0    65            NaN
2    MSFT  -1.00     85.0    64     bill gates
3    RIL     NaN     50.0  1023  mukesh ambani
4    TATA   5.60      NaN  n.a.     ratan tata

In [8]:
df.columns

Index(['tickers', 'eps', 'revenue', 'price', 'people'], dtype='object')

In [9]:
df.to_csv("new.csv",columns=["tickers","eps"])

In [10]:
df.to_csv("new.csv",header = False)

In [11]:
df

  tickers    eps  revenue price         people
0   GOOGL  27.82     87.0   845     larry page
1     WMT   4.61    484.0    65            NaN
2    MSFT  -1.00     85.0    64     bill gates
3    RIL     NaN     50.0  1023  mukesh ambani
4    TATA   5.60      NaN  n.a.     ratan tata

In [12]:
import pandas as pd
def convert_people_cell(cell):
    if cell == "n.a.":
        return 'sam walton'
    return cell
df = pd.read_excel("stock_data.xlsx","Sheet1",converters = {
        'people' : convert_people_cell
    })
df

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65     sam walton
2    MSFT             -1       85    64     bill gates
3    RIL   not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata


                      Write to Excel

In [13]:
df.to_excel("new.xlsx",sheet_name="stocks",startrow=1,startcol=2)

        Write two dataframes to two separate sheets in excel

In [14]:
df_stocks = pd.DataFrame({
    'tickers': ['GOOGL', 'WMT', 'MSFT'],
    'price': [845, 65, 64 ],
    'pe': [30.37, 14.26, 30.97],
    'eps': [27.82, 4.61, 2.12]
})

df_weather =  pd.DataFrame({
    'day': ['1/1/2017','1/2/2017','1/3/2017'],
    'temperature': [32,35,28],
    'event': ['Rain', 'Sunny', 'Snow']
})

In [15]:
with pd.ExcelWriter('stocks_weather.xlsx') as writer:
    df_stocks.to_excel(writer, sheet_name="stocks")
    df_weather.to_excel(writer, sheet_name="weather")