                                                Different Ways of Creating DataFrame

In [1]:
#1 Data frame for CSV file
import pandas as pd
df = pd.read_csv("weather_data.csv")
df

          day  temperature  windspeed   event
0  01-01-2017         32.0        6.0    Rain
1  01-04-2017          NaN        9.0   Sunny
2  01-05-2017         28.0        NaN    Snow
3  01-06-2017          NaN        7.0     NaN
4  01-07-2017         32.0        NaN    Rain
5  01-08-2017          NaN        NaN   Sunny
6  01-09-2017          NaN        NaN     NaN
7  01-10-2017         34.0        8.0  Cloudy
8  01-11-2017         40.0       12.0   Sunny

In [2]:
#2. Data frame for excel file
df = pd.read_excel("weather_data.xlsx")
df

         day  temperature  windspeed  event
0 2017-01-01           32          6   Rain
1 2017-01-02           35          7  Sunny
2 2017-01-03           28          2   Snow

In [3]:
#3. Data frame for dictionary
weather_data = {
    'day': ['1/1/2017','1/2/2017','1/3/2017','1/4/2017','1/5/2017','1/6/2017'],
    'temperature': [32,35,28,24,32,31],
    'windspeed': [6,7,2,7,4,2],
    'event': ['Rain', 'Sunny', 'Snow','Snow','Rain', 'Sunny']
}
df = pd.DataFrame(weather_data)
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [4]:
#4 Tuples list 
weather_data = [
    ('1/1/2017',32,6,'Rain'),
    ('1/2/2017',35,7,'Sunny'),
    ('1/3/2017',28,2,'Snow')
]
df = pd.DataFrame(weather_data,columns=["day","temperature","windspeed","Event"])
#when we are creating tuple list we need to specify the columns to create dataframe
df

        day  temperature  windspeed  Event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

In [5]:
#5 List of dictionary
weather_data = [
    {'day': '1/1/2017', 'temperature': 32, 'windspeed': 6, 'event': 'Rain'},
    {'day': '1/2/2017', 'temperature': 35, 'windspeed': 7, 'event': 'Sunny'},
    {'day': '1/3/2017', 'temperature': 28, 'windspeed': 2, 'event': 'Snow'},
    
]
df = pd.DataFrame(weather_data)
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow