            Read and write Data from Database

In [1]:
import pandas as pd
import sqlalchemy
from sqlalchemy import create_engine

In [2]:
engine = create_engine('mysql+pymysql://root:bloom%400205@localhost:3306/applications')

In [3]:
df = pd.read_sql_table("customers",engine)
df

   id    name  phone_number
0   1  Donald    7326784567
1   2    Bill    6573489999
2   3    Modi    4567895646

In [4]:
df = pd.read_sql_table("customers", engine, columns=["name"])
df

     name
0  Donald
1    Bill
2    Modi

Join two tables and read them in a dataframe using read_sql_query

In [5]:
query = '''
 SELECT customers.name, customers.phone_number, orders.name, orders.amount
 FROM customers INNER JOIN orders
 ON customers.id=orders.customer_id
'''
df=pd.read_sql(query,engine)
df

     name  phone_number          name  amount
0  Donald    7326784567  Google Pixel   950.0
1    Bill    6573489999      Yoga Mat    20.0
2    Modi    4567895646  Fossil Watch   120.0

In [6]:
df = pd.read_csv("customers.csv")
df

     Customer Name  Customer Phone
0     rafael nadal      4567895647
1  maria sharapova       434534545
2   vladimir putin        89345345
3      kim un jong       123434456
4       jeff bezos       934534543
5     rahul gandhi        44324222

In [7]:
df.rename(columns={
    'Customer Name': 'name',
    'Customer Phone': 'phone_number'
}, inplace=True)
df

              name  phone_number
0     rafael nadal    4567895647
1  maria sharapova     434534545
2   vladimir putin      89345345
3      kim un jong     123434456
4       jeff bezos     934534543
5     rahul gandhi      44324222

In [10]:
df.to_sql(
    name='customers',
    con=engine,
    if_exists='append',
    index=False
)

6

In [11]:
pd.read_sql("customers",engine)

   id             name  phone_number
0   1           Donald    7326784567
1   2             Bill    6573489999
2   3             Modi    4567895646
3   4     rafael nadal    4567895647
4   5  maria sharapova     434534545
5   6   vladimir putin      89345345
6   7      kim un jong     123434456
7   8       jeff bezos     934534543
8   9     rahul gandhi      44324222