Yearly Period

In [1]:
import pandas as pd
y = pd.Period('2016')
y

Period('2016', 'Y-DEC')

In [2]:
y.start_time

Timestamp('2016-01-01 00:00:00')

In [3]:
y.end_time

Timestamp('2016-12-31 23:59:59.999999999')

In [4]:
y.is_leap_year

True

Monthly Period

In [5]:
m = pd.Period('2017-12')
m

Period('2017-12', 'M')

In [6]:
m.start_time

Timestamp('2017-12-01 00:00:00')

In [7]:
m.end_time

Timestamp('2017-12-31 23:59:59.999999999')

In [8]:
m+1

Period('2018-01', 'M')

Daily Period

In [9]:
d = pd.Period('2016-02-28', freq='D')
d

Period('2016-02-28', 'D')

In [10]:
d.start_time

Timestamp('2016-02-28 00:00:00')

In [11]:
d.end_time

Timestamp('2016-02-28 23:59:59.999999999')

In [12]:
d+1

Period('2016-02-29', 'D')

Hourly Period

In [13]:
h = pd.Period('2017-08-15 23:00:00',freq='h')
h

Period('2017-08-15 23:00', 'h')

In [14]:
h+1

Period('2017-08-16 00:00', 'h')

Achieve same results using pandas offsets hour

In [15]:
h+pd.offsets.Hour(1)

Period('2017-08-16 00:00', 'h')

Quarterly Period

In [16]:
q1= pd.Period('2017Q1', freq='Q-JAN')
q1

Period('2017Q1', 'Q-JAN')

In [17]:
q1.start_time

Timestamp('2016-02-01 00:00:00')

In [18]:
q1.end_time

Timestamp('2016-04-30 23:59:59.999999999')

Use asfreq to convert period to a different frequency

In [19]:
q1.asfreq('M',how='start')

Period('2016-02', 'M')

In [20]:
q1.asfreq('M',how='end')

Period('2016-04', 'M')

Weekly Period

In [21]:
w = pd.Period('2017-07-05',freq='W')
w

Period('2017-07-03/2017-07-09', 'W-SUN')

In [22]:
w-1

Period('2017-06-26/2017-07-02', 'W-SUN')

In [23]:
w2 = pd.Period('2017-08-15',freq='W')
w2

Period('2017-08-14/2017-08-20', 'W-SUN')

In [24]:
w2-w

PeriodIndex and period_range

In [25]:
r = pd.period_range('2011', '2017', freq='Q')
r

PeriodIndex(['2011Q1', '2011Q2', '2011Q3', '2011Q4', '2012Q1', '2012Q2',
             '2012Q3', '2012Q4', '2013Q1', '2013Q2', '2013Q3', '2013Q4',
             '2014Q1', '2014Q2', '2014Q3', '2014Q4', '2015Q1', '2015Q2',
             '2015Q3', '2015Q4', '2016Q1', '2016Q2', '2016Q3', '2016Q4',
             '2017Q1'],
            dtype='period[Q-DEC]')

In [26]:
r[0].start_time

Timestamp('2011-01-01 00:00:00')

In [27]:
r[0].end_time

Timestamp('2011-03-31 23:59:59.999999999')

Walmart's fiscal year ends in Jan, below is how you generate walmart's fiscal quarters between 2011 and 2017

In [28]:
r = pd.period_range('2011', '2017', freq='Q-JAN')
r

PeriodIndex(['2011Q4', '2012Q1', '2012Q2', '2012Q3', '2012Q4', '2013Q1',
             '2013Q2', '2013Q3', '2013Q4', '2014Q1', '2014Q2', '2014Q3',
             '2014Q4', '2015Q1', '2015Q2', '2015Q3', '2015Q4', '2016Q1',
             '2016Q2', '2016Q3', '2016Q4', '2017Q1', '2017Q2', '2017Q3',
             '2017Q4'],
            dtype='period[Q-JAN]')

In [29]:
r[0].start_time

Timestamp('2010-11-01 00:00:00')

In [30]:
r[0].end_time

Timestamp('2011-01-31 23:59:59.999999999')

In [31]:
r = pd.period_range(start='2016-01', freq='3M', periods=10)
r

PeriodIndex(['2016-01', '2016-04', '2016-07', '2016-10', '2017-01', '2017-04',
             '2017-07', '2017-10', '2018-01', '2018-04'],
            dtype='period[3M]')

In [32]:
import pandas as pd
import numpy as np

idx = pd.date_range('2016-01-01', periods=10)

ps = pd.Series(np.random.randn(len(idx)), index=idx)

ps

2016-01-01   -0.174874
2016-01-02    1.304834
2016-01-03    0.261539
2016-01-04   -1.392222
2016-01-05   -0.639557
2016-01-06    0.321061
2016-01-07   -0.098606
2016-01-08   -0.113911
2016-01-09   -0.733391
2016-01-10    0.764795
Freq: D, dtype: float64

Partial Indexing

In [33]:
ps['2016']

2016-01-01   -0.174874
2016-01-02    1.304834
2016-01-03    0.261539
2016-01-04   -1.392222
2016-01-05   -0.639557
2016-01-06    0.321061
2016-01-07   -0.098606
2016-01-08   -0.113911
2016-01-09   -0.733391
2016-01-10    0.764795
Freq: D, dtype: float64

In [34]:
ps['2016':'2017']

2016-01-01   -0.174874
2016-01-02    1.304834
2016-01-03    0.261539
2016-01-04   -1.392222
2016-01-05   -0.639557
2016-01-06    0.321061
2016-01-07   -0.098606
2016-01-08   -0.113911
2016-01-09   -0.733391
2016-01-10    0.764795
Freq: D, dtype: float64

Converting between representations

In [35]:
idx = pd.period_range('2016-01', periods=5, freq='3M')

ps = pd.Series(np.random.randn(len(idx)), index=idx)

pst = ps.to_timestamp()

pst

2016-01-01   -0.912628
2016-04-01   -0.197286
2016-07-01   -1.257344
2016-10-01    1.313514
2017-01-01    0.713134
Freq: QS-OCT, dtype: float64

In [36]:
pst.index

DatetimeIndex(['2016-01-01', '2016-04-01', '2016-07-01', '2016-10-01',
               '2017-01-01'],
              dtype='datetime64[ns]', freq='QS-OCT')

In [37]:
ps = pst.to_period()
ps

2016Q1   -0.912628
2016Q2   -0.197286
2016Q3   -1.257344
2016Q4    1.313514
2017Q1    0.713134
Freq: Q-DEC, dtype: float64

In [38]:
ps.index

PeriodIndex(['2016Q1', '2016Q2', '2016Q3', '2016Q4', '2017Q1'], dtype='period[Q-DEC]')

Processing Wal Mart's Financials

In [39]:
import pandas as pd
df = pd.read_csv("wmt.csv")
df

  Line Item  2017Q1  2017Q2  2017Q3  2017Q4  2018Q1
0   Revenue  115904  120854  118179  130936  117542
1  Expenses   86544   89485   87484   97743   87688
2    Profit   29360   31369   30695   33193   29854

In [40]:
df.set_index("Line Item",inplace=True)
df = df.T
df

Line Item  Revenue  Expenses  Profit
2017Q1      115904     86544   29360
2017Q2      120854     89485   31369
2017Q3      118179     87484   30695
2017Q4      130936     97743   33193
2018Q1      117542     87688   29854

In [41]:
df.index = pd.PeriodIndex(df.index, freq="Q-JAN")
df

Line Item  Revenue  Expenses  Profit
2017Q1      115904     86544   29360
2017Q2      120854     89485   31369
2017Q3      118179     87484   30695
2017Q4      130936     97743   33193
2018Q1      117542     87688   29854

In [42]:
df.index

PeriodIndex(['2017Q1', '2017Q2', '2017Q3', '2017Q4', '2018Q1'], dtype='period[Q-JAN]')

In [43]:
df.index[0].start_time

Timestamp('2016-02-01 00:00:00')

Add start date end date columns to dataframe

In [44]:
df["Start Date"]=df.index.map(lambda x: x.start_time)
df

Line Item  Revenue  Expenses  Profit Start Date
2017Q1      115904     86544   29360 2016-02-01
2017Q2      120854     89485   31369 2016-05-01
2017Q3      118179     87484   30695 2016-08-01
2017Q4      130936     97743   33193 2016-11-01
2018Q1      117542     87688   29854 2017-02-01

In [45]:
df["End Date"]=df.index.map(lambda x: x.end_time)
df

Line Item  Revenue  Expenses  Profit Start Date                      End Date
2017Q1      115904     86544   29360 2016-02-01 2016-04-30 23:59:59.999999999
2017Q2      120854     89485   31369 2016-05-01 2016-07-31 23:59:59.999999999
2017Q3      118179     87484   30695 2016-08-01 2016-10-31 23:59:59.999999999
2017Q4      130936     97743   33193 2016-11-01 2017-01-31 23:59:59.999999999
2018Q1      117542     87688   29854 2017-02-01 2017-04-30 23:59:59.999999999