                                                            DataFrame Basics

In [1]:
import pandas as pd
weather_data = {
    'day': ['1/1/2017','1/2/2017','1/3/2017','1/4/2017','1/5/2017','1/6/2017'],
    'temperature': [32,35,28,24,32,31],
    'windspeed': [6,7,2,7,4,2],
    'event': ['Rain', 'Sunny', 'Snow','Snow','Rain', 'Sunny']
}
df = pd.DataFrame(weather_data) # to read the data from pyhton dictionary
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [2]:
df.shape #to get the number of columns and rows in table

(6, 4)

In [3]:
rows,columns = df.shape

In [4]:
rows

6

In [5]:
columns

4

In [6]:
df.head() #initial few rows

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain

In [7]:
df.tail() # last 5 rows

        day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [8]:
df.tail(1) # for last 1 row

        day  temperature  windspeed  event
5  1/6/2017           31          2  Sunny

In [9]:
df[2:5] # To print row number 2 to 4 it's like slicing in python

        day  temperature  windspeed event
2  1/3/2017           28          2  Snow
3  1/4/2017           24          7  Snow
4  1/5/2017           32          4  Rain

In [10]:
df.columns

Index(['day', 'temperature', 'windspeed', 'event'], dtype='object')

In [11]:
df.day # To print individual column

0    1/1/2017
1    1/2/2017
2    1/3/2017
3    1/4/2017
4    1/5/2017
5    1/6/2017
Name: day, dtype: object

In [12]:
df['day'] #df.day both are similar

0    1/1/2017
1    1/2/2017
2    1/3/2017
3    1/4/2017
4    1/5/2017
5    1/6/2017
Name: day, dtype: object

In [13]:
type(df['event'])

pandas.core.series.Series

In [14]:
df[['event','day']] # to print how many columns I want

   event       day
0   Rain  1/1/2017
1  Sunny  1/2/2017
2   Snow  1/3/2017
3   Snow  1/4/2017
4   Rain  1/5/2017
5  Sunny  1/6/2017

In [15]:
df['temperature'].max()

35

In [16]:
df['temperature'].min()

24

In [17]:
df['temperature'].mean()

np.float64(30.333333333333332)

In [18]:
df['temperature'].std()

3.8297084310253524

In [19]:
df.describe() # To print the statistics

       temperature  windspeed
count     6.000000   6.000000
mean     30.333333   4.666667
std       3.829708   2.338090
min      24.000000   2.000000
25%      28.750000   2.500000
50%      31.500000   5.000000
75%      32.000000   6.750000
max      35.000000   7.000000

In [20]:
df[df.temperature>=32]

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
4  1/5/2017           32          4   Rain

In [21]:
df[df.temperature == df.temperature.max()]

        day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny

In [22]:
df['day'][df.temperature == df.temperature.max()]

1    1/2/2017
Name: day, dtype: object

In [23]:
df.index

RangeIndex(start=0, stop=6, step=1)

In [24]:
df.set_index('day') #after updating the index it doesn't change orginal data frame it just updates until u set as inpalce = true

          temperature  windspeed  event
day
1/1/2017           32          6   Rain
1/2/2017           35          7  Sunny
1/3/2017           28          2   Snow
1/4/2017           24          7   Snow
1/5/2017           32          4   Rain
1/6/2017           31          2  Sunny

In [25]:
df.set_index('day',inplace=True)

In [26]:
df

          temperature  windspeed  event
day
1/1/2017           32          6   Rain
1/2/2017           35          7  Sunny
1/3/2017           28          2   Snow
1/4/2017           24          7   Snow
1/5/2017           32          4   Rain
1/6/2017           31          2  Sunny

In [27]:
df.loc['1/2/2017']

temperature       35
windspeed          7
event          Sunny
Name: 1/2/2017, dtype: object

In [28]:
df.reset_index(inplace = True) #if we want original table we can use reset method 
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [29]:
df.set_index('event',inplace = True)

In [30]:
df

            day  temperature  windspeed
event
Rain   1/1/2017           32          6
Sunny  1/2/2017           35          7
Snow   1/3/2017           28          2
Snow   1/4/2017           24          7
Rain   1/5/2017           32          4
Sunny  1/6/2017           31          2

In [31]:
df.loc['Snow']

            day  temperature  windspeed
event
Snow   1/3/2017           28          2
Snow   1/4/2017           24          7